

INSERT INTO `items` (`a`, `b`, `listID`) VALUES
("Strecke", "<math> <mrow> <mi>s</mi> <mo stretchy='false'>=</mo> <mrow> <mfrac> <mn>1</mn> <mn>2</mn> </mfrac> <mo stretchy='false'>⋅</mo> <mi>a</mi> <mo stretchy='false'>⋅</mo> <msup> <mi>t</mi> <mn>2</mn> </msup> </mrow> </mrow> </math>", 20),
("Geschwindigkeit", "<math> <mrow> <mi>v</mi> <mo stretchy='false'>=</mo> <mfrac> <mrow> <mi>∆</mi> <mi>s</mi> </mrow> <mrow> <mi>∆</mi> <mi>t</mi> </mrow> </mfrac> </mrow> </math>", 20),
("Beschleunigung", "<math> <mrow> <mi>a</mi> <mo stretchy='false'>=</mo> <mfrac> <mrow> <mi>∆</mi> <mi>v</mi> </mrow> <mrow> <mi>∆</mi> <mi>t</mi> </mrow> </mfrac> </mrow> </math>", 20),
("Kinetische Energie", "<math> <mrow> <mrow> <msub> <mi>W</mi> <mi mathvariant='italic'>kin</mi> </msub> <mo stretchy='false'>=</mo> <mfrac> <mn>1</mn> <mn>2</mn> </mfrac> </mrow> <mi>m</mi> <msup> <mi>v</mi> <mn>2</mn> </msup> </mrow> </math>", 20),
("Bewegungsenergie", "<math> <mrow> <mi>W</mi> <mo stretchy='false'>=</mo> <mrow> <mi>m</mi> <mo stretchy='false'>⋅</mo> <mi>g</mi> <mo stretchy='false'>⋅</mo> <mi>h</mi> </mrow> </mrow> </math>", 20),
("Fläche eines Kreises", "<math> <mrow> <mrow> <mi>A</mi> <mo stretchy='false'>=</mo> <mrow> <mi>π</mi> <mo stretchy='false'>⋅</mo> <msup> <mi>r</mi> <mn>2</mn> </msup> </mrow> </mrow> <mi>;</mi> <mrow> <mi>r</mi> <mo stretchy='false'>=</mo> <mfrac> <mi>d</mi> <mn>2</mn> </mfrac> </mrow> </mrow> </math>", 20),
("Leistung", "<math> <mrow> <mi>P</mi> <mo stretchy='false'>=</mo> <mfrac> <mi>W</mi> <mi>t</mi> </mfrac> </mrow> </math>", 20);

INSERT INTO `items` (`a`, `b`, `listID`) VALUES
("Ohm´sche Gesetz", "<math> <mrow> <mi>R</mi> <mo stretchy='false'>=</mo> <mfrac> <mi>U</mi> <mi>I</mi> </mfrac> </mrow> </math>", 21),
("Stromstärke", "<math> <mrow> <mi>I</mi> <mo stretchy='false'>=</mo> <mfrac> <mrow> <mi>∆</mi> <mi>Q</mi> </mrow> <mrow> <mi>∆</mi> <mi>t</mi> </mrow> </mfrac> </mrow> </math>", 21),
("Anzahl Elektronen", "<math> <mrow> <mi>n</mi> <mo stretchy='false'>=</mo> <mfrac> <mi>Q</mi> <mi>e</mi> </mfrac> </mrow> </math>", 21),
("Wiederstand Reihenschaltung", "<math> <mrow> <msub> <mi>R</mi> <mi mathvariant='italic'>ges</mi> </msub> <mo stretchy='false'>=</mo> <mrow> <msub> <mi>R</mi> <mn>1</mn> </msub> <mo stretchy='false'>+</mo> <msub> <mi>R</mi> <mn>2</mn> </msub> <mo stretchy='false'>+</mo> <mi>…</mi> </mrow> </mrow> </math>", 21),
("Stromstäre Reihenschaltung", "<math> <mrow> <msub> <mi>I</mi> <mi mathvariant='italic'>ges</mi> </msub> <mo stretchy='false'>=</mo> <msub> <mi>I</mi> <mn>1</mn> </msub> <mo stretchy='false'>=</mo> <msub> <mi>I</mi> <mn>2</mn> </msub> <mo stretchy='false'>=</mo> <mi>…</mi> </mrow> </math>", 21),
("Spannung Reihenschaltung", "<math> <mrow> <msub> <mi>U</mi> <mi mathvariant='italic'>ges</mi> </msub> <mo stretchy='false'>=</mo> <mrow> <msub> <mi>U</mi> <mn>1</mn> </msub> <mo stretchy='false'>+</mo> <msub> <mi>U</mi> <mn>2</mn> </msub> <mo stretchy='false'>+</mo> <mi>…</mi> </mrow> </mrow> </math>", 21),
("Wiederstand Parallelschaltung", "<math> <mrow> <mfrac> <mn>1</mn> <msub> <mi>R</mi> <mi mathvariant='italic'>ges</mi> </msub> </mfrac> <mo stretchy='false'>=</mo> <mrow> <mfrac> <mn>1</mn> <msub> <mi>R</mi> <mn>1</mn> </msub> </mfrac> <mo stretchy='false'>+</mo> <mfrac> <mn>1</mn> <msub> <mi>R</mi> <mn>2</mn> </msub> </mfrac> <mo stretchy='false'>+</mo> <mi>…</mi> </mrow> </mrow> </math>", 21),
("Stromstärke Parallelschaltung", "<math> <mrow> <msub> <mi>I</mi> <mi mathvariant='italic'>ges</mi> </msub> <mo stretchy='false'>=</mo> <mrow> <msub> <mi>I</mi> <mn>1</mn> </msub> <mo stretchy='false'>+</mo> <msub> <mi>I</mi> <mn>2</mn> </msub> <mo stretchy='false'>+</mo> <mi>…</mi> </mrow> </mrow> </math>", 21),
("Spannung Parallelschaltung", "<math> <mrow> <msub> <mi>U</mi> <mi mathvariant='italic'>ges</mi> </msub> <mo stretchy='false'>=</mo> <msub> <mi>U</mi> <mn>1</mn> </msub> <mo stretchy='false'>=</mo> <msub> <mi>U</mi> <mn>2</mn> </msub> <mo stretchy='false'>=</mo> <mi>…</mi> </mrow> </math>", 21),
("el. Feldstärke", "<math> <mrow> <mi>E</mi> <mo stretchy='false'>=</mo> <mfrac> <mi>U</mi> <mi>d</mi> </mfrac> </mrow> </math>", 21),
("Kraft E-Feld", "<math> <mrow> <msub> <mi>F</mi> <mi mathvariant='italic'>el</mi> </msub> <mo stretchy='false'>=</mo> <mrow> <mi>q</mi> <mo stretchy='false'>⋅</mo> <mi>E</mi> </mrow> </mrow> </math>", 21),
("Kapazität im Kondensator", "<math> <mrow> <mi>C</mi> <mo stretchy='false'>=</mo> <mfrac> <mi>Q</mi> <mi>U</mi> </mfrac> </mrow> </math>", 21),
("Kapazität im Kondensator", "<math> <mrow> <mrow> <mi>C</mi> <mo stretchy='false'>=</mo> <mrow> <msub> <mi>E</mi> <mn>0</mn> </msub> <mo stretchy='false'>⋅</mo> <msub> <mi>E</mi> <mi>r</mi> </msub> </mrow> </mrow> <mfrac> <mi>A</mi> <mi>d</mi> </mfrac> </mrow> </math>", 21),
("Energie im Kondensator", "<math> <mrow> <mrow> <msub> <mi>W</mi> <mi mathvariant='italic'>kon</mi> </msub> <mo stretchy='false'>=</mo> <mfrac> <mn>1</mn> <mn>2</mn> </mfrac> </mrow> <mrow> <mi>Q</mi> <mo stretchy='false'>⋅</mo> <mi>U</mi> </mrow> </mrow> </math>", 21),
("Flächenladungsdichte", "<math> <mrow> <mi>σ</mi> <mo stretchy='false'>=</mo> <mfrac> <mi>Q</mi> <mi>A</mi> </mfrac> <mo stretchy='false'>=</mo> <mrow> <mi>E</mi> <mo stretchy='false'>⋅</mo> <msub> <mi>E</mi> <mn>0</mn> </msub> </mrow> </mrow> </math>", 21),
("Beschleunigung eines Elektron (e-Feld hom)", "<math> <mrow> <mi>a</mi> <mo stretchy='false'>=</mo> <mfrac> <mrow> <mi>E</mi> <mo stretchy='false'>⋅</mo> <mi>e</mi> </mrow> <msub> <mi>m</mi> <mi>e</mi> </msub> </mfrac> </mrow> </math>", 21),
("Kinetische Energie eines Elektrons", "<math> <mrow> <msub> <mi>W</mi> <mi mathvariant='italic'>kin</mi> </msub> <mo stretchy='false'>=</mo> <mrow> <msub> <mi>q</mi> <mi>e</mi> </msub> <mo stretchy='false'>⋅</mo> <mi>U</mi> </mrow> </mrow> </math>", 21),
("Maximale Entropie", "<math> <mrow> <mi>∆</mi> <mrow> <mi>S</mi> <mo stretchy='false'>=</mo> <mfrac> <mrow> <mi>∆</mi> <mi>W</mi> </mrow> <mi>T</mi> </mfrac> </mrow> </mrow> </math>", 21),
("Coulomb-Kräfte", "<math> <mrow> <mi>F</mi> <mo stretchy='false'>=</mo> <mfrac> <mrow> <mi>k</mi> <mo stretchy='false'>⋅</mo> <mi>Q</mi> <mo stretchy='false'>⋅</mo> <mi>q</mi> </mrow> <msup> <mi>r</mi> <mn>2</mn> </msup> </mfrac> </mrow> </math>", 21);

INSERT INTO `items` (`a`, `b`, `listID`) VALUES
("Kapazität in Reihenschaltung", "<math> <mrow> <mfrac> <mn>1</mn> <msub> <mi>C</mi> <mi mathvariant='italic'>ges</mi> </msub> </mfrac> <mo stretchy='false'>=</mo> <mrow> <mfrac> <mn>1</mn> <msub> <mi>C</mi> <mn>1</mn> </msub> </mfrac> <mo stretchy='false'>+</mo> <mfrac> <mn>1</mn> <msub> <mi>C</mi> <mn>2</mn> </msub> </mfrac> <mo stretchy='false'>+</mo> <mi>…</mi> </mrow> </mrow> </math>", 22),
("Kapazität in Parallelschaltung", "<math> <mrow> <mi>C</mi> <mo stretchy='false'>=</mo> <mrow> <msub> <mi>C</mi> <mn>1</mn> </msub> <mo stretchy='false'>+</mo> <msub> <mi>C</mi> <mn>2</mn> </msub> <mo stretchy='false'>+</mo> <mi>…</mi> </mrow> </mrow> </math>", 22),
("Spannung", "<math> <mrow> <msub> <mi>U</mi> <mi mathvariant='italic'>ges</mi> </msub> <mo stretchy='false'>=</mo> <mrow> <msub> <mi>U</mi> <mi mathvariant='italic'>Quelle</mi> </msub> <mo stretchy='false'>−</mo> <msub> <mi>U</mi> <mi mathvariant='italic'>Kondensator</mi> </msub> </mrow> </mrow> </math>", 22),
("Ladung in Abhängigkeit zur Zeit", "<math> <mrow> <mi>Q</mi> <mrow> <mrow> <mo fence='true' stretchy='true'>(</mo> <mrow> <mi>t</mi> </mrow> <mo fence='true' stretchy='true'>)</mo> </mrow> <mo stretchy='false'>=</mo> <mrow> <mrow> <mi>C</mi> <mo stretchy='false'>⋅</mo> <msub> <mi>U</mi> <mi>q</mi> </msub> </mrow> <mo stretchy='false'>−</mo> <mrow> <mi>C</mi> <mo stretchy='false'>⋅</mo> <msub> <mi>U</mi> <mi>q</mi> </msub> <mo stretchy='false'>⋅</mo> <msup> <mi>e</mi> <mfrac> <mrow> <mo stretchy='false'>−</mo> <mn>1</mn> </mrow> <mrow> <mi>R</mi> <mo stretchy='false'>⋅</mo> <mi>C</mi> </mrow> </mfrac> </msup> <mo stretchy='false'>⋅</mo> <mi>t</mi> </mrow> </mrow> </mrow> </mrow> </math>", 22),
("1. Ableitung von <mover accent='true'> <mi>Q</mi> </mover><mrow> <mo fence='true' stretchy='true'>(</mo> <mrow> <mi>t</mi> </mrow> <mo fence='true' stretchy='true'>)</mo> </mrow>", "<math> <mrow> <mover accent='true'> <mi>Q</mi> <mo stretchy='false'>˙</mo> </mover> <mrow> <mrow> <mo fence='true' stretchy='true'>(</mo> <mrow> <mi>t</mi> </mrow> <mo fence='true' stretchy='true'>)</mo> </mrow> <mo stretchy='false'>=</mo> <mrow> <mfrac> <msub> <mi>U</mi> <mi>q</mi> </msub> <mi>R</mi> </mfrac> <mo stretchy='false'>−</mo> <mrow> <mfrac> <mn>1</mn> <mrow> <mi>R</mi> <mo stretchy='false'>⋅</mo> <mi>C</mi> </mrow> </mfrac> <mo stretchy='false'>⋅</mo> <mi>Q</mi> </mrow> </mrow> </mrow> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mi>t</mi> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> </mrow> </math>", 22);

INSERT INTO `items` (`a`, `b`, `listID`) VALUES
("m. Feldstärke (Spule)", "<math> <mrow> <mrow> <mi>B</mi> <mo stretchy='false'>=</mo> <mrow> <msub> <mi>μ</mi> <mn>0</mn> </msub> <mo stretchy='false'>⋅</mo> <msub> <mi>μ</mi> <mi>r</mi> </msub> </mrow> </mrow> <mfrac> <mrow> <mi>I</mi> <mo stretchy='false'>⋅</mo> <mi>n</mi> </mrow> <mi>l</mi> </mfrac> </mrow> </math>", 23),
("Hallspannung", "<math> <mrow> <msub> <mi>U</mi> <mi>H</mi> </msub> <mo stretchy='false'>=</mo> <mrow> <mi>v</mi> <mo stretchy='false'>⋅</mo> <mi>B</mi> <mo stretchy='false'>⋅</mo> <mi>b</mi> </mrow> <mo stretchy='false'>=</mo> <mfrac> <mrow> <msub> <mi>R</mi> <mi>H</mi> </msub> <mo stretchy='false'>⋅</mo> <mi>I</mi> <mo stretchy='false'>⋅</mo> <mi>B</mi> </mrow> <mi>d</mi> </mfrac> </mrow> </math>", 23),
("Hallkonstante", "<math> <mrow> <msub> <mi>R</mi> <mi>H</mi> </msub> <mo stretchy='false'>=</mo> <mfrac> <mn>1</mn> <mrow> <mi>n</mi> <mo stretchy='false'>⋅</mo> <mi>e</mi> </mrow> </mfrac> </mrow> </math>", 23),
("Induktionsspannung", "<math> <mrow> <msub> <mi>U</mi> <mi mathvariant='italic'>Ind</mi> </msub> <mo stretchy='false'>=</mo> <mrow> <mrow> <mo stretchy='false'>−</mo> <mi>B</mi> </mrow> <mo stretchy='false'>⋅</mo> <mi>l</mi> <mo stretchy='false'>⋅</mo> <mi>v</mi> <mo stretchy='false'>⋅</mo> <mi>n</mi> </mrow> </mrow> </math><math> <mrow> <mrow /> <mo stretchy='false'>−</mo> <mrow> <mi>n</mi> <mo stretchy='false'>⋅</mo> <mover accent='true'> <mi>∅</mi> <mo stretchy='false'>˙</mo> </mover> </mrow> </mrow> </math>", 23),
("Magnetischer Fluss", "<math> <mrow> <mover accent='true'> <mi>∅</mi> <mo stretchy='false'>˙</mo> </mover> <mo stretchy='false'>=</mo> <mover accent='true'> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mrow> <mi>B</mi> <mo stretchy='false'>⋅</mo> <mi>A</mi> </mrow> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> <mo stretchy='false'>˙</mo> </mover> </mrow> </math>", 23),
("Energie in der Spule", "<math> <mrow> <mrow> <msub> <mi>E</mi> <mi>L</mi> </msub> <mo stretchy='false'>=</mo> <mfrac> <mn>1</mn> <mn>2</mn> </mfrac> </mrow> <mrow> <mi>L</mi> <mo stretchy='false'>⋅</mo> <msup> <mi>I</mi> <mn>2</mn> </msup> </mrow> </mrow> </math>", 23),
("Lorenzkraft", "<math> <mrow> <msub> <mi>F</mi> <mi>L</mi> </msub> <mo stretchy='false'>=</mo> <mrow> <mrow> <mo fence='true' stretchy='true'>(</mo> <mrow> <mi>n</mi> </mrow> <mo fence='true' stretchy='true'>)</mo> </mrow> <mo stretchy='false'>⋅</mo> <mi>e</mi> <mo stretchy='false'>⋅</mo> <mi>B</mi> <mo stretchy='false'>⋅</mo> <mi>v</mi> </mrow> </mrow> </math><br><math> <mrow> <msub> <mi>F</mi> <mi>L</mi> </msub> <mo stretchy='false'>=</mo> <mrow> <mi>I</mi> <mo stretchy='false'>⋅</mo> <mi>B</mi> <mo stretchy='false'>⋅</mo> <mi>s</mi> <mo stretchy='false'>⋅</mo> <mi>n</mi> </mrow> </mrow> </math>", 23),
("Zentripetalkraft", "<math> <mrow> <msub> <mi>F</mi> <mi>Z</mi> </msub> <mo stretchy='false'>=</mo> <mfrac> <mrow> <mi>m</mi> <mo stretchy='false'>⋅</mo> <msup> <mi>v</mi> <mn>2</mn> </msup> </mrow> <mi>r</mi> </mfrac> </mrow> </math>", 23),
("Kraft Spule in Soule", "<math> <mrow> <mi>F</mi> <mo stretchy='false'>=</mo> <mrow> <msub> <mi>n</mi> <mn>2</mn> </msub> <mo stretchy='false'>⋅</mo> <mi>B</mi> <mo stretchy='false'>⋅</mo> <mi>I</mi> <mo stretchy='false'>⋅</mo> <msub> <mi>s</mi> <mrow> <mi mathvariant='italic'>Katnenlänge</mi> <mi mathvariant='italic'>äA</mi> </mrow> </msub> </mrow> </mrow> </math>", 23),
("Verweildauer", "<math> <mrow> <mi>T</mi> <mo stretchy='false'>=</mo> <mfrac> <mrow> <mn>2</mn> <mrow> <mi>π</mi> <mo stretchy='false'>⋅</mo> <mi>r</mi> </mrow> </mrow> <mi>v</mi> </mfrac> </mrow> </math>", 23),
("Schraubenbahn", "<math> <mrow> <mrow> <mi>T</mi> <mo stretchy='false'>=</mo> <mn>2</mn> </mrow> <mfrac> <mrow> <mi>π</mi> <mo stretchy='false'>⋅</mo> <mi>m</mi> </mrow> <mrow> <mi>e</mi> <mo stretchy='false'>⋅</mo> <mi>B</mi> </mrow> </mfrac> </mrow> </math>", 23),
("Schraubenbahn", "<math> <mrow> <mi>r</mi> <mo stretchy='false'>=</mo> <mfrac> <mrow> <mi>v</mi> <mo stretchy='false'>⋅</mo> <mi>m</mi> </mrow> <mrow> <mi>B</mi> <mo stretchy='false'>⋅</mo> <mi>e</mi> </mrow> </mfrac> </mrow> </math>", 23);

INSERT INTO `items` (`a`, `b`, `listID`) VALUES
("Induktivität einer Spule", "<math> <mrow> <mi>L</mi> <mo stretchy='false'>=</mo> <mrow> <mfrac> <mrow> <mrow> <mo stretchy='false'>−</mo> <msub> <mi>μ</mi> <mn>0</mn> </msub> </mrow> <mo stretchy='false'>⋅</mo> <msub> <mi>μ</mi> <mi>r</mi> </msub> <mo stretchy='false'>⋅</mo> <msup> <mi>n</mi> <mn>2</mn> </msup> </mrow> <mi>l</mi> </mfrac> <mo stretchy='false'>⋅</mo> <mi>A</mi> </mrow> </mrow> </math>", 24),
("Induktivität einer Spule (Ableitung)", "<math> <mrow> <mi>L</mi> <mo stretchy='false'>=</mo> <mfrac> <msub> <mi>U</mi> <mn>0</mn> </msub> <mover accent='true'> <mrow> <mi>I</mi> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mi>t</mi> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> </mrow> <mo stretchy='false'>˙</mo> </mover> </mfrac> </mrow> </math>", 24);

INSERT INTO `items` (`a`, `b`, `listID`) VALUES
("Weg-Zeit-Gesetz", "<math> <mrow> <mi>s</mi> <mrow> <mrow> <mo fence='true' stretchy='true'>(</mo> <mrow> <mi>t</mi> </mrow> <mo fence='true' stretchy='true'>)</mo> </mrow> <mo stretchy='false'>=</mo> <mrow> <msub> <mi>s</mi> <mi mathvariant='italic'>max</mi> </msub> <mo stretchy='false'>⋅</mo> <mi>sin</mi> </mrow> </mrow> <mi>⁡</mi> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mrow> <mrow> <mi>ω</mi> <mo stretchy='false'>⋅</mo> <mi>t</mi> </mrow> <mo stretchy='false'>+</mo> <mi>φ</mi> </mrow> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> </mrow> </math>", 25),
("1. Ableitung Weg-Zeit-Gesetz", "<math> <mrow> <mi>v</mi> <mrow> <mrow> <mo fence='true' stretchy='true'>(</mo> <mrow> <mi>t</mi> </mrow> <mo fence='true' stretchy='true'>)</mo> </mrow> <mo stretchy='false'>=</mo> <mrow> <msub> <mi>v</mi> <mi mathvariant='italic'>max</mi> </msub> <mo stretchy='false'>⋅</mo> <mi>sin</mi> </mrow> </mrow> <mi>⁡</mi> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mrow> <mrow> <mi>ω</mi> <mo stretchy='false'>⋅</mo> <mi>t</mi> </mrow> <mo stretchy='false'>+</mo> <mi>φ</mi> </mrow> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> </mrow> </math><br><math> <mrow> <msub> <mi>v</mi> <mi mathvariant='italic'>max</mi> </msub> <mo stretchy='false'>=</mo> <mrow> <msub> <mi>s</mi> <mi mathvariant='italic'>max</mi> </msub> <mo stretchy='false'>⋅</mo> <mi>ω</mi> </mrow> </mrow> </math>", 25),
("2. Ableitung Weg-Zeit-Gesetz", "<math> <mrow> <mi>a</mi> <mrow> <mrow> <mo fence='true' stretchy='true'>(</mo> <mrow> <mi>t</mi> </mrow> <mo fence='true' stretchy='true'>)</mo> </mrow> <mo stretchy='false'>=</mo> <mrow> <mrow> <mo stretchy='false'>−</mo> <msub> <mi>a</mi> <mi mathvariant='italic'>max</mi> </msub> </mrow> <mo stretchy='false'>⋅</mo> <mi>sin</mi> </mrow> </mrow> <mi>⁡</mi> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mrow> <mrow> <mi>ω</mi> <mo stretchy='false'>⋅</mo> <mi>t</mi> </mrow> <mo stretchy='false'>+</mo> <mi>φ</mi> </mrow> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> </mrow> </math><br><math> <mrow> <msub> <mi>a</mi> <mi mathvariant='italic'>max</mi> </msub> <mo stretchy='false'>=</mo> <mrow> <msub> <mi>s</mi> <mi mathvariant='italic'>max</mi> </msub> <mo stretchy='false'>⋅</mo> <msup> <mi>ω</mi> <mn>2</mn> </msup> </mrow> </mrow> </math>", 25),
("Hooksches Gesetz", "<math> <mrow> <mi>F</mi> <mo stretchy='false'>=</mo> <mrow> <mi>D</mi> <mo stretchy='false'>⋅</mo> <mi>s</mi> </mrow> </mrow> </math>", 25),
("Kraft U-Rohr", "<math> <mrow> <mi>F</mi> <mo stretchy='false'>=</mo> <mrow> <mi>ρ</mi> <mo stretchy='false'>⋅</mo> <mi>V</mi> <mo stretchy='false'>⋅</mo> <mi>g</mi> </mrow> </mrow> </math>", 25),
("Frequenz", "<math> <mrow> <mi>f</mi> <mo stretchy='false'>=</mo> <mfrac> <mn>1</mn> <mi>T</mi> </mfrac> </mrow> </math>", 25),
("Winkelgkeit / Kreisfrequenz", "<math> <mrow> <mrow> <mi>ω</mi> <mo stretchy='false'>=</mo> <mn>2</mn> </mrow> <mrow> <mi mathvariant='italic'>πf</mi> <mo stretchy='false'>=</mo> <mfrac> <mrow> <mi>∆</mi> <mi>φ</mi> </mrow> <mrow> <mi>∆</mi> <mi>t</mi> </mrow> </mfrac> </mrow> </mrow> </math>", 25),
("Federkonstante (horizo. Fadenpendel)", "<math> <mrow> <msub> <mi>D</mi> <mi mathvariant='italic'>ges</mi> </msub> <mo stretchy='false'>=</mo> <mrow> <msub> <mi>D</mi> <mn>1</mn> </msub> <mo stretchy='false'>+</mo> <msub> <mi>D</mi> <mn>2</mn> </msub> </mrow> </mrow> </math>", 25),
("Federkonstante seriell", "<math> <mrow> <mfrac> <mn>1</mn> <msub> <mi>D</mi> <mi mathvariant='italic'>ges</mi> </msub> </mfrac> <mo stretchy='false'>=</mo> <mrow> <mfrac> <mn>1</mn> <msub> <mi>D</mi> <mn>1</mn> </msub> </mfrac> <mo stretchy='false'>+</mo> <mfrac> <mn>1</mn> <msub> <mi>D</mi> <mn>2</mn> </msub> </mfrac> </mrow> </mrow> </math>", 25),
("Spannenergie", "<math> <mrow> <mrow> <msub> <mi>E</mi> <mi mathvariant='italic'>Spann</mi> </msub> <mo stretchy='false'>=</mo> <mfrac> <mn>1</mn> <mn>2</mn> </mfrac> </mrow> <mi>D</mi> <msup> <mi>s</mi> <mn>2</mn> </msup> </mrow> </math>", 25),
("Schwingungsdauer Federpendel", "<math> <mrow> <mi>ω</mi> <mo stretchy='false'>=</mo> <msqrt> <mfrac> <mi>D</mi> <mi>m</mi> </mfrac> </msqrt> <mo stretchy='false'>=</mo> <msqrt> <mfrac> <mi>g</mi> <mi>l</mi> </mfrac> </msqrt> </mrow> </math>", 25),
("Schwingungsdauer U-Rohr", "<math> <mrow> <mi>ω</mi> <mo stretchy='false'>=</mo> <msqrt> <mfrac> <mrow> <mn>2</mn> <mo stretchy='false'>⋅</mo> <mi>g</mi> </mrow> <mi>l</mi> </mfrac> </msqrt> </mrow> </math>", 25);

INSERT INTO `items` (`a`, `b`, `listID`) VALUES
("LC-Schwingkreis", "<math> <mrow> <mi>ω</mi> <mo stretchy='false'>=</mo> <msqrt> <mfrac> <mn>1</mn> <mrow> <mi>L</mi> <mo stretchy='false'>⋅</mo> <mi>C</mi> </mrow> </mfrac> </msqrt> </mrow> </math>", 26),
("DGL", "<math> <mrow> <mover accent='true'> <mi>Q</mi> <mo stretchy='false'>¨</mo> </mover> <mrow> <mrow> <mo fence='true' stretchy='true'>(</mo> <mrow> <mi>t</mi> </mrow> <mo fence='true' stretchy='true'>)</mo> </mrow> <mo stretchy='false'>=</mo> <mrow> <mfrac> <mrow> <mo stretchy='false'>−</mo> <mn>1</mn> </mrow> <mrow> <mi>L</mi> <mo stretchy='false'>⋅</mo> <mi>C</mi> </mrow> </mfrac> <mo stretchy='false'>⋅</mo> <mi>Q</mi> </mrow> </mrow> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mi>t</mi> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> </mrow> </math><br><math> <mrow> <mi>Q</mi> <mrow> <mrow> <mo fence='true' stretchy='true'>(</mo> <mrow> <mi>t</mi> </mrow> <mo fence='true' stretchy='true'>)</mo> </mrow> <msup> <mo stretchy='false'>=</mo> <mi>Q</mi> </msup> <mrow /> </mrow> <mi>cos</mi> <mi>⁡</mi> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mrow> <mi>ω</mi> <mo stretchy='false'>⋅</mo> <mi>t</mi> </mrow> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> </mrow> </math>", 26),
("Stromstärke", "<math> <mrow> <mi>I</mi> <mrow> <mrow> <mo fence='true' stretchy='true'>(</mo> <mrow> <mi>t</mi> </mrow> <mo fence='true' stretchy='true'>)</mo> </mrow> <mo stretchy='false'>=</mo> <mrow> <mi>Î</mi> <mo stretchy='false'>⋅</mo> <mi>sin</mi> </mrow> </mrow> <mi>⁡</mi> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mrow> <mi>ω</mi> <mo stretchy='false'>⋅</mo> <mi>t</mi> </mrow> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> </mrow> </math>", 26);

INSERT INTO `items` (`a`, `b`, `listID`) VALUES
("Allgemeine Schwingungsgleichung", "<math> <mrow> <mi>y</mi> <mrow> <mrow> <mo fence='true' stretchy='true'>(</mo> <mrow> <mi>t</mi> </mrow> <mo fence='true' stretchy='true'>)</mo> </mrow> <msup> <mo stretchy='false'>=</mo> <mi>y</mi> </msup> <mrow /> </mrow> <mi>sin</mi> <mrow> <mo fence='true' stretchy='true'>(</mo> <mrow> <mrow> <mi mathvariant='italic'>ωt</mi> <mo stretchy='false'>+</mo> <mi>φ</mi> </mrow> </mrow> <mo fence='true' stretchy='true'>)</mo> </mrow> </mrow> </math>", 27),
("Allgemeine Wellengleichung", "<math> <mrow> <mi>y</mi> <mrow> <mrow> <mo fence='true' stretchy='true'>(</mo> <mrow> <mrow> <mi>t</mi> <mi>,</mi> <mi>x</mi> </mrow> </mrow> <mo fence='true' stretchy='true'>)</mo> </mrow> <msup> <mo stretchy='false'>=</mo> <mi>y</mi> </msup> <mrow /> </mrow> <mi>sin</mi> <mrow> <mo fence='true' stretchy='true'>(</mo> <mrow> <mrow> <mn>2</mn> <mi>π</mi> <mrow> <mo fence='true' stretchy='true'>(</mo> <mrow> <mrow> <mfrac> <mi>t</mi> <mi>T</mi> </mfrac> <mo stretchy='false'>−</mo> <mfrac> <mi>x</mi> <mi>λ</mi> </mfrac> </mrow> </mrow> <mo fence='true' stretchy='true'>)</mo> </mrow> </mrow> </mrow> <mo fence='true' stretchy='true'>)</mo> </mrow> </mrow> </math>", 27),
("Wellenlänge / Ausbreitungsgeschwindigkeit / Frequenz", "<math> <mrow> <mi>c</mi> <mo stretchy='false'>=</mo> <mrow> <mi>λ</mi> <mo stretchy='false'>⋅</mo> <mi>f</mi> </mrow> </mrow> </math>", 27),
("Eigenschwingungslänge", "<math> <mrow> <mi>l</mi> <mo stretchy='false'>=</mo> <mrow> <mfrac> <mrow> <mi>k</mi> <mo stretchy='false'>⋅</mo> <mi>λ</mi> </mrow> <mn>2</mn> </mfrac> <mo stretchy='false'>∨</mo> <mi>k</mi> </mrow> <mo stretchy='false'>=</mo> <mi>N</mi> </mrow> </math>", 27),
("Eigenschwingungsfrequenz", "<math> <mrow> <msub> <mi>f</mi> <mi>k</mi> </msub> <mo stretchy='false'>=</mo> <mrow> <mfrac> <mrow> <mi>k</mi> <mo stretchy='false'>⋅</mo> <mi>c</mi> </mrow> <mrow> <mn>2</mn> <mi>l</mi> </mrow> </mfrac> <mo stretchy='false'>∨</mo> <mi>k</mi> </mrow> <mo stretchy='false'>=</mo> <mi>N</mi> </mrow> </math>", 27);

INSERT INTO `items` (`a`, `b`, `listID`) VALUES
("Gangunterschied (k.I.)", "<math> <mrow> <mi>∆</mi> <mrow> <mi>s</mi> <mo stretchy='false'>=</mo> <mrow> <mrow> <mi>k</mi> <mo stretchy='false'>⋅</mo> <mi>λ</mi> </mrow> <mo stretchy='false'>∨</mo> <mi>k</mi> </mrow> <mo stretchy='false'>=</mo> <mi>Z</mi> </mrow> </mrow> </math>", 28),
("Gangunterschied (d.I.)", "<math> <mrow> <mi>∆</mi> <mrow> <mi>s</mi> <mo stretchy='false'>=</mo> <mrow> <mfrac> <mrow> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mrow> <mn>2</mn> <mrow> <mi>k</mi> <mo stretchy='false'>+</mo> <mn>1</mn> </mrow> </mrow> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> <mo stretchy='false'>⋅</mo> <mi>λ</mi> </mrow> <mn>2</mn> </mfrac> <mo stretchy='false'>∨</mo> <mi mathvariant='italic'>kZ</mi> </mrow> </mrow> </mrow> </math>", 28),
("Position k-tes Maximum (Doppelspalt/Gitter)", "<math> <mrow> <mrow> <mi>sin</mi> <mi>⁡</mi> <mrow> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mrow> <mi>∝</mi> <mrow /> <mrow> <mrow /> <mi>k</mi> </mrow> </mrow> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> <mo stretchy='false'>=</mo> <mfrac> <mrow> <mi>k</mi> <mo stretchy='false'>⋅</mo> <mi>λ</mi> </mrow> <mi>g</mi> </mfrac> </mrow> </mrow> <mrow /> </mrow> </math>", 28),
("Position k-tes Minimum (Doppelspalt/Gitter)", "<math> <mrow> <mrow> <mi>sin</mi> <mi>⁡</mi> <mrow> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mrow> <mi>∝</mi> <mrow /> <mrow> <mrow /> <mi>k</mi> </mrow> </mrow> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> <mo stretchy='false'>=</mo> <mfrac> <mrow> <mfrac> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mrow> <mn>2</mn> <mrow> <mi>k</mi> <mo stretchy='false'>−</mo> <mn>1</mn> </mrow> </mrow> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> <mn>2</mn> </mfrac> <mo stretchy='false'>⋅</mo> <mi>λ</mi> </mrow> <mi>g</mi> </mfrac> </mrow> </mrow> <mrow /> </mrow> </math>", 28),
("Position k-tes Maximum (Einzelspalt)", "<math> <mrow> <mrow> <mi>sin</mi> <mi>⁡</mi> <mrow> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mrow> <mi>∝</mi> <mrow /> <mrow> <mrow /> <mi>k</mi> </mrow> </mrow> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> <mo stretchy='false'>=</mo> <mfrac> <mrow> <mfrac> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mrow> <mn>2</mn> <mrow> <mi>k</mi> <mo stretchy='false'>−</mo> <mn>1</mn> </mrow> </mrow> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> <mn>2</mn> </mfrac> <mo stretchy='false'>⋅</mo> <mi>λ</mi> </mrow> <mi>b</mi> </mfrac> </mrow> </mrow> <mrow /> </mrow> </math>", 28),
("Position k-tes Minimum (Einzelspalt)", "<math> <mrow> <mrow> <mi>sin</mi> <mi>⁡</mi> <mrow> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mrow> <mi>∝</mi> <mrow /> <mrow> <mrow /> <mi>k</mi> </mrow> </mrow> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> <mo stretchy='false'>=</mo> <mfrac> <mrow> <mi>k</mi> <mo stretchy='false'>⋅</mo> <mi>λ</mi> </mrow> <mi>b</mi> </mfrac> </mrow> </mrow> <mrow /> </mrow> </math>", 28),
("Beugungswinkel", "<math> <mrow> <mrow> <mi>tan</mi> <mi>⁡</mi> <mrow> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mrow> <mi>∝</mi> <mrow /> <mrow> <mrow /> <mi>k</mi> </mrow> </mrow> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> <mo stretchy='false'>=</mo> <mfrac> <msub> <mi>d</mi> <mi>k</mi> </msub> <mi>a</mi> </mfrac> </mrow> </mrow> <mrow /> </mrow> </math>", 28),
("Phasendifferenz Gitter", "<math> <mrow> <mi>∆</mi> <mrow> <mi>φ</mi> <mo stretchy='false'>=</mo> <mn>2</mn> </mrow> <mfrac> <mrow> <mi>π</mi> <mo stretchy='false'>⋅</mo> <mrow> <mi>∆</mi> <mi>s</mi> </mrow> </mrow> <mi>λ</mi> </mfrac> </mrow> </math>", 28),
("Gitterkonstante", "<math> <mrow> <mi>50/mm</mi> <mo stretchy='false'>≙</mo> <mi>g</mi> <mo stretchy='false'>=</mo> <mrow> <mfrac> <mn>1</mn> <mn>50</mn> </mfrac> <mo stretchy='false'>⋅</mo> <msup> <mn>10</mn> <mrow> <mo stretchy='false'>−</mo> <mn>3</mn> </mrow> </msup> </mrow> </mrow> </math>", 28),
("Lage der Minima", "<math> <mfrac> <msub> <mi>d</mi> <mn>1</mn> </msub> <mrow> <mi>n</mi> <mo stretchy='false'>−</mo> <mi mathvariant='italic'>Spalte</mi> </mrow> </mfrac> </math>", 28);

INSERT INTO `items` (`a`, `b`, `listID`) VALUES
("Energie eines Quantenobjekts", "<math> <mrow> <mi>E</mi> <mo stretchy='false'>=</mo> <mrow> <mi>h</mi> <mo stretchy='false'>⋅</mo> <mi>f</mi> </mrow> </mrow> </math>", 29),
("De-Broglie-Wellenlänge eines Quantenobjekts", "<math> <mrow> <mi>λ</mi> <mo stretchy='false'>=</mo> <mfrac> <mi>h</mi> <mi>p</mi> </mfrac> <mo stretchy='false'>=</mo> <mfrac> <mi>h</mi> <mrow> <mi>m</mi> <mo stretchy='false'>⋅</mo> <mi>v</mi> </mrow> </mfrac> </mrow> </math>", 29),
("Energie-Masse-Beziehung", "<math> <mrow> <mi>E</mi> <mo stretchy='false'>=</mo> <mrow> <mi>m</mi> <mo stretchy='false'>⋅</mo> <msup> <mi>c</mi> <mn>2</mn> </msup> </mrow> </mrow> </math>", 29),
("Äußerer Photoeffekt für Licht/Photonen", "<math> <mrow> <msub> <mi>E</mi> <mi mathvariant='italic'>Ph</mi> </msub> <mo stretchy='false'>=</mo> <mrow> <mrow> <mi>h</mi> <mo stretchy='false'>⋅</mo> <mi>f</mi> </mrow> <mo stretchy='false'>−</mo> <msub> <mi>E</mi> <mi>A</mi> </msub> </mrow> </mrow> </math>", 29),
("Bragg-G für Beugung Qo. am Gitterkristall (zwei Netzebenen)", "<math> <mrow> <mn>2</mn> <mrow> <mi>d</mi> <mo stretchy='false'>⋅</mo> <mi>sin</mi> </mrow> <mi>⁡</mi> <mrow> <mrow> <mo fence='true' stretchy='false'>(</mo> <mrow> <mrow> <mn>2</mn> <mo stretchy='false'>⋅</mo> <mi>φ</mi> </mrow> </mrow> <mo fence='true' stretchy='false'>)</mo> </mrow> <mo stretchy='false'>=</mo> <mrow> <mi>k</mi> <mo stretchy='false'>⋅</mo> <mi>λ</mi> </mrow> </mrow> </mrow> </math>", 29),
("Unschärferelation (Impuls-Ort)", "<math> <mrow> <mi>h</mi> <mi>≤</mi> <mi>∆</mi> <mrow> <mi>x</mi> <mo stretchy='false'>⋅</mo> <mi>∆</mi> </mrow> <mi>p</mi> </mrow> </math>", 29),
("Wellen", "<math> <mrow> <mi>sin</mi> <mrow> <mrow> <mn>2</mn> <mi>φ</mi> </mrow> <mo stretchy='false'>=</mo> <mfrac> <mi>r</mi> <mi>l</mi> </mfrac> <mo stretchy='false'>=</mo> <mfrac> <mrow> <mi>k</mi> <mo stretchy='false'>⋅</mo> <mi>λ</mi> </mrow> <mi>d</mi> </mfrac> </mrow> </mrow> </math>", 29);